--1

SQLPLUS SYSTEM/0000;

--
CREATE USER ORCLUSER
IDENTIFIED BY AAAA;

--

GRANT UNLIMITED TABLESPACE to ORCLUSER;

--

GRANT CREATE SESSION TO ORCLUSER;


--

GRANT CREATE TABLE TO ORCLUSER;

--

conn ORCLUSER/AAAA;

--2
/*CREATE DEPT TABLE*/

CREATE TABLE DEPT (
    DEPTNO NUMBER(2),
    DNAME VARCHAR(40),
    LOC VARCHAR(40)
);

DESC DEPT;

--3
/*CREATE EMP TABLE*/

CREATE TABLE  EMP (
  EMPNO NUMBER(4),
  ENAME VARCHAR(40),
  JOB VARCHAR(40),
  HIREDATE DATE,
  SAL NUMBER(7),
  COMM NUMBER(7),
  DEPTNO NUMBER(7)
  
);

DESC EMP;

--4
/*NOT NULL*/
ALTER TABLE DEPT MODIFY(DEPTNO NOT NULL);

ALTER TABLE EMP MODIFY(EMPNO NOT NULL);

--5
/*PRIMARY KEY*/

ALTER TABLE DEPT ADD PRIMARY KEY(DEPTNO);


ALTER TABLE EMP ADD PRIMARY KEY(EMPNO);

--6

ALTER TABLE EMP
ADD FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO);

--7
INSERT ALL
    INTO DEPT(DEPTNO, DNAME, LOC) VALUES (10, '아나운서부', '서울시')
    INTO DEPT(DEPTNO, DNAME, LOC) VALUES (20, '연출부', '서울시')
    INTO DEPT(DEPTNO, DNAME, LOC) VALUES (30, '기획부', '서울시')
    INTO DEPT(DEPTNO, DNAME, LOC) VALUES (40, '편집부', '서울시')
    INTO DEPT(DEPTNO, DNAME, LOC) VALUES (50, '취재부', '경기도')
    INTO DEPT(DEPTNO, DNAME, LOC) VALUES (60, '문화예술부', '경기도')
SELECT * FROM DUAL;

--8
INSERT ALL
    INTO EMP(EMPNO, ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)
        VALUES (7369, '지연우', '아나운서', '2024/01/05', 1100, 300, 10)
    INTO EMP(EMPNO, ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)
        VALUES (7499, '김수빈', '작가', '2023/01/02', 1200, NULL, 20)
    INTO EMP(EMPNO, ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)
        VALUES (7521, '이지훈', '기획부장', '2021/03/02', 1300, 200, 30)
    INTO EMP(EMPNO, ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)
        VALUES (7566, '김나비', '편집PD', '2023/05/12', 1400, NULL, 40)
    INTO EMP(EMPNO, ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)
        VALUES (7654, '임진우', '기자', '2023/07/24', 1200, NULL, 50)
    INTO EMP(EMPNO, ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)
        VALUES (7678, '김신실', '감독', '2020/11/02', 1100, 100, 60)
SELECT * FROM DUAL;

--9
SELECT * FROM EMP, DEPT 

--10

SELECT E.EMPNO,E.ENAME,D.DEPTNO,D.DNAME,D.LOC

FROM EMP E,DEPT D

WHERE E.DEPTNO = D.DEPTNO

ORDER BY DEPTNO;


--11

SELECT * FROM EMP
WHERE DEPTNO IN (30);

--12

SELECT E.DEPTNO, E.EMPNO 
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
ORDER BY E.DEPTNO, E.EMPNO;

SELECT E.DEPTNO, E.EMPNO 
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO 
ORDER BY E.EMPNO;

--13
SELECT ENAME, SUBSTR(ENAME, 1,1)
  FROM EMP

--14

SELECT *
FROM EMP
WHERE DEPTNO = 50 AND ENAME ='임진우';

--15
create table EMP_TEMP2 AS
select * from EMP;

commit;

select * from EMP_TEMP2;


--16

DELETE 
  FROM EMP_TEMP2
 WHERE EMPNO = 7566
 

--17
SELECT ENAME,SAL 
FROM EMP 
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='임진우');


--18
select ENAME, length(ENAME)
from EMP;


--19
select DEPTNO,JOB,AVG(SAL) 
from EMP
group by DEPTNO
having avg(SAL) >= 1300;

--20

SET serveroutput ON;
DECLARE    
    v_num NUMBER := 0; -- 시작숫자    
    v_tot_num NUMBER := 0; -- 총 loop수 반환 변수
BEGIN   
    WHILE v_num < 5 LOOP        
    DBMS_OUTPUT.PUT_LINE('현재 i의 값: ' || v_num);        
    v_num := v_num + 1;        
    v_tot_num := v_tot_num + 1;        
    -- EXIT WHEN v_num > 5;    
    END LOOP;    
    DBMS_OUTPUT.PUT_LINE(v_tot_num || '번의 LOOP');
END;
